### ISSUE TITLE
Scrolling does not load

### ISSUE THREAD

**Issue by hermannsblum** [ArthurClemens/mithril-infinite#10]
I am trying to create a very simple example, but there are some things that are really not clear to me.
This is my setup:

```
view: function() {
    return m('div', {style: 'height: 600px;'}, m(List, {
      header: {
        title: 'the title'
      },
      tiles: m(infinite, {
        item,
        pageData,
      }),
    }));
  }
```

I also made sure that `html` has a height of `100%`.

What happens with the above example is that first, the div get's overflown, so infinite is actually much bigger than the height of `600px`. Then the first two pages are loaded, and when scrolling to the end nothing happens. I can see neither network requests nor any errors in the console. What am I doing wrong here?

**Comment by ArthurClemens** [comment]
Did you solve the issue?

**Comment by hermannsblum** [comment]
Yes, solved it
I still have no idea what the error was

The biggest problem is that there are never any error messages, it is super hard to debug. Are you catching errors or are there some code paths that just terminate without feedback?
