### ISSUE TITLE
Why is m.redraw being used inside the view?

### ISSUE THREAD

**Issue by nordfjord** [ArthurClemens/mithril-infinite#2]
See [here](https://github.com/ArthurClemens/mithril-infinite/blob/master/lib/mithril-infinite.es6.js#L240)

since `m.redraw` does nothing if it's already redrawing, which if you're in a view I'd think is nearly _all_ the time, doesn't this simply not work?

Wouldn't it be wiser to put it inside a `setTimeout` so that the current stack finishes before redraw is called again?

**Comment by ArthurClemens** [comment]
You can put `m.redraw` inside the view and cause an endless loop, so normally it is bad practice.

Putting this inside `setTimeout` gives worse performance.

**Comment by barneycarroll** [comment]
@nordfjord's right, a redraw triggered during the draw step is a no-op - see this [demo](http://jsbin.com/samomu/edit?js,output): `m.redraw()` calls during view computation have no effect.

**Comment by ArthurClemens** [comment]
Weird. I see a clear difference:
1. Leave out m.redraw: "short" example gets stuck, no more parts are drawn
2. Put m.redraw insite setTimeout: scrolling feels noticeably more stutter-y

**Comment by ArthurClemens** [comment]
In any case, putting it in setTimeout fixes the "short" example on Chrome Windows.

**Comment by nordfjord** [comment]
you could of course use `requestAnimationFrame` in stead of `setTimeout`, and to support IE8 something like:

``` js
const rAF = window.requestAnimationFrame || window.setTimeout;
```

That should fix some of the performance issues, since in the best case `requestAnimationFrame` runs directly after the stack, and in the best case `setTimeout` has a 4ms delay.
