### ISSUE TITLE
Refresh component on demand

### ISSUE THREAD

**Issue by shekharsom** [ArthurClemens/mithril-infinite#28]
Sometimes, the page data is expected to be cached but updated later once server response is received. If a page data is returned from cache but updated later, there should be some provision to refresh the component.

**Comment by chrislim** [comment]
I think I'm facing a similar situation where I want to enable the user to delete an entry in the list. The underlying data is changing, but the cached page data is not refreshing.

**Comment by ArthurClemens** [comment]
I think that in both cases `pageKey` could be used. See [Handling dynamic data](https://github.com/ArthurClemens/mithril-infinite#handling-dynamic-data).

**Comment by shekharsom** [comment]
pageKey solved it.
