### ISSUE TITLE
NPM install pulls down Mithril

### ISSUE THREAD

**Issue by JohnPaulHarold** [ArthurClemens/mithril-infinite#3]
When I try to install this via NPM, on windows it pulls down mithril. However, on OSX, it will pull down correctly (along with j2c).

A small image of the issue

![image](https://cloud.githubusercontent.com/assets/9934306/22572404/f03fc36c-e99b-11e6-8a63-fb244bb7532b.png)

**Comment by ArthurClemens** [comment]
I have no idea what is the cause of this. I find it suspicious that your node_modules is nested, instead of one flat list. Is your npm up to date?

**Comment by JohnPaulHarold** [comment]
Was on `v5.9.0` and updated to the latest, so am now on `node -v
v6.9.5 && npm -v 3.10.10`. I forgot to get the version of `npm` from earlier. I also, just for good measure, wiped the `node_modules` folder and installed again. I'm still seeing the same outcome.

**Comment by ArthurClemens** [comment]
I found 2 issues.

1. I found that package.json still had a "files" entry pointing to a no longer used directory. I have updated the package to 0.6.1 and now it works correctly.

2. You are still working on older node. The latest versions that I downloaded from https://nodejs.org/en/download/current/ :

* node version 7.5.0
* npm version 4.1.2

**Comment by JohnPaulHarold** [comment]
thanks. One or both of those fixed things. I now see a `/dist/` folder in my module folder.

I've updated to `v1.0.0` of Mithril so I'll probably checkout your `rewrite` branch.

**Comment by ArthurClemens** [comment]
I am finishing up rewrite as we speak.

**Comment by JohnPaulHarold** [comment]
brilliant. One issue-ette, npm install fails due to lack of require `name` field in `package.json`

**Comment by ArthurClemens** [comment]
Weird, I see `name` in [package.json 0.6.1](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/package.json#L2) and in [package.json 1.0.0](https://github.com/ArthurClemens/mithril-infinite/blob/rewrite/packages/mithril-infinite/package.json#L2).

**Comment by JohnPaulHarold** [comment]
my bad with the confusion, I meant it fails for me on the rewrite branch, because of a lack of `name` prop.
