### ISSUE TITLE
Code improvement suggestions

### ISSUE THREAD

**Issue by dead-claudia** [ArthurClemens/mithril-infinite#4]
I was taking a gander at your `mithril-infinite`, and noticed a few things that could be done differently:

1. [Why these pointless `Object.assign` calls](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L135-L160), when you could just return the literal instead? (That's one of many in that file alone.)

2. [This `setTimeout`](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L70-L77) is redundant ~~in light of the above~~ (edit: forgot to remove this part), and is completely unused elsewhere.

3. [This `removeEventListener`](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L82) will never remove the `scroll` event handler you think it will because the handler is always created afresh for each instance.

    You should instead set it as a `state` property in the [main `oninit`](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L118) and just directly add/remove the event listener here in [this node](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L215-L235). This will simplify the code and eliminate a memory leak.

4. I would do [this](https://github.com/ArthurClemens/mithril-infinite/blob/master/packages/mithril-infinite/src/index.js#L191-L212) in a frame-throttled `resize` event handler, to only force a style recalc when the `state.scrollView` element is resized, rather than on *every* redraw. In addition, it's a chance to schedule a redraw to update the UI in case it's resized without the user updating anything.

**Comment by ArthurClemens** [comment]
Thank you for your comments.

1. True
2. There are 2 timers at play. The goal of the first one is to notify when scrolling is done; the timer id is reset at each scroll; the isScrolling state is passed to pages, that can do their own optimisations based on this. The goal of the second one is to throttle the updates to the scroll view, and only call redraw every 200ms - which does optimise the scrolling experience a bit. How is the setTimeout redundant?
3. Yep, I see now: with `onremove` a new `scroll` function is created.
4. Resizing also takes place when with collapse. So it may be optimised, but it should take changes in content size into account.

**Comment by dead-claudia** [comment]
> How is the setTimeout redundant?

Both calls use the same timeout value (`state.scrollThrottle`), which is where I was coming from. In addition, the second one (the one I referenced) is never cleared like the other is.

As for "in light of the above", just pretend that didn't exist (see the edit). 😉 

> Resizing also takes place when with collapse.

So if there's an event to detect that, too, then you can just use those rather than Mithril's view layer.

**Comment by ArthurClemens** [comment]
> Both calls use the same timeout value (state.scrollThrottle) 

That means that the "no longer scrolling" state is effective at the same moment when the last "update while scrolling" redraw happens. That first timeout could be another arbitrary value, but will be harder to reason about.

The second one only needs to be cleared if you set the first timeout to a lower value than the second, and want to prevent the second one to call redraw. With the current values, the second one just times out naturally.

MutationObserver, check.

**Comment by dead-claudia** [comment]
Oh okay. I see now.

**Comment by ArthurClemens** [comment]
I've added some optimisations in version 1.1.0.
