### ISSUE TITLE
Scroll Direction

### ISSUE THREAD

**Issue by Kethku** [ArthurClemens/mithril-infinite#7]
I'm looking at using this tool for a chat application and I have a few questions.

1. Can you set the scroll direction? Chat applications traditionally add new content to the bottom of the chat log and you scroll up to see more. I'd like to use this to simulate that user experience.

2. Page size. How well does this handle dynamically sized content. When I load in some of the messages, it is impossible to tell how tall the message will be until it finishes rendering. Will this tool handle this well and adjust?

3. Pinning. If I have a chat application and the user is at the bottom of the chat, when new messages come in I would like to rerender the chat with the new message and scrolled all the way to the bottom. However if the user is not at the bottom and they scroll up, it makes sense to not move the chat log and keep the current location. Do you have any suggestions for this problem?

Thanks for your time. And sorry if this isn't the correct place to ask.

**Comment by ArthurClemens** [comment]
1. mithril-infinite doesn't change scrolling behavior. There is no "inverse" scroll. But you can add items at the beginning, then use javascript to scroll the content div to the top.
1. Content of different sizes and changing sizes are handled well.
1. This might cause a usability problem. User has scrolled, but new content is added to the top. This will cause the content to scroll. A solution could be to not render the new element until the user has scrolled to the top themselves. That is something your application needs to handle.
